INSERT INTO topics (code, title, module, type, filepath) VALUES
('m0t1', 'Что такое DevOps', 0, 'topic', 'modules/m0/m0t1_Что такое DevOps.md'),
('m0t2', 'Жизненный цикл разработки (SDLC)', 0, 'topic', 'modules/m0/m0t2_Жизненный цикл разработки (SDLC).md'),
('m0t3', 'DevOps vs SRE vs Agile', 0, 'topic', 'modules/m0/m0t3_DevOps vs SRE vs Agile.md'),
('m0t4', 'Непрерывная разработка и интеграция (CI & CD)', 0, 'topic', 'modules/m0/m0t4_Непрерывная разработка и интеграция (CI & CD).md'),
('p0', 'End-to-End Pipeline', 0, 'practice', 'practices/p0_End-to-End Pipeline.md'),
('km0', 'Ключевые моменты', 0, 'keypoints', 'keypoints/km0_Ключевые моменты.md'),
('testm0', 'Тестирование', 0, 'test', 'tests/testm0_Тестирование.md'),
('m1t1', 'IT-системы и ОС Linux', 1, 'topic', 'modules/m1/m1t1_IT-системы и ОС Linux.md'),
('m1t2', 'Операционная система Linux', 1, 'topic', 'modules/m1/m1t2_Операционная система Linux.md'),
('m1t3', 'Администрирование Linux', 1, 'topic', 'modules/m1/m1t3_Администрирование Linux.md'),
('m1t4', 'Программирование на Bash', 1, 'topic', 'modules/m1/m1t4_Программирование на Bash.md'),
('p1', 'Автоматизация рутинных задач', 1, 'practice', 'practices/p1_Автоматизация рутинных задач.md'),
('km1', 'Ключевые моменты', 1, 'keypoints', 'keypoints/km1_Ключевые моменты.md'),
('testm1', 'Тестирование', 1, 'test', 'tests/testm1_Тестирование.md'),
('m2t1', 'Теоретические основы сети', 2, 'topic', 'modules/m2/m2t1_Теоретические основы сети.md'),
('m2t2', 'Практика', 2, 'topic', 'modules/m2/m2t2_Практика.md'),
('p2', 'Настройка сети в VM', 2, 'practice', 'practices/p2_Настройка сети в VM.md'),
('km2', 'Ключевые моменты', 2, 'keypoints', 'keypoints/km2_Ключевые моменты.md'),
('testm2', 'Тестирование', 2, 'test', 'tests/testm2_Тестирование.md'),
('m3t1', 'Виртуализация', 3, 'topic', 'modules/m3/m3t1_Виртуализация.md'),
('m3t2', 'Docker & Kubernetes', 3, 'topic', 'modules/m3/m3t2_Docker & Kubernetes.md'),
('p3', 'Развертывание веб-приложения', 3, 'practice', 'practices/p3_Развертывание веб-приложения.md'),
('km3', 'Ключевые моменты', 3, 'keypoints', 'keypoints/km3_Ключевые моменты.md'),
('testm3', 'Тестирование', 3, 'test', 'tests/testm3_Тестирование.md'),
('m4t1', 'Основы IaC и управление конфигурацией', 4, 'topic', 'modules/m4/m4t1_Основы IaC и управление конфигурацией.md'),
('m4t2', 'Ansible', 4, 'topic', 'modules/m4/m4t2_Ansible.md'),
('m4t3', 'Terraform', 4, 'topic', 'modules/m4/m4t3_Terraform.md'),
('m4t4', 'CI & CD системы', 4, 'topic', 'modules/m4/m4t4_CI & CD системы.md'),
('p4', 'Автоматизация инфраструктуры', 4, 'practice', 'practices/p4_Автоматизация инфраструктуры.md'),
('km4', 'Ключевые моменты', 4, 'keypoints', 'keypoints/km4_Ключевые моменты.md'),
('testm4', 'Тестирование', 4, 'test', 'tests/testm4_Тестирование.md'),
('m5t1', 'Основы наблюдаемости', 5, 'topic', 'modules/m5/m5t1_Основы наблюдаемости.md'),
('m5t2', 'Зачем мониторинг', 5, 'topic', 'modules/m5/m5t2_Зачем мониторинг.md'),
('m5t3', 'ELK & EFK', 5, 'topic', 'modules/m5/m5t3_ELK & EFK.md'),
('m5t4', 'Zabbix & Sentry', 5, 'topic', 'modules/m5/m5t4_Zabbix & Sentry.md'),
('p5', 'Настройка мониторинга', 5, 'practice', 'practices/p5_Настройка мониторинга.md'),
('km5', 'Ключевые моменты', 5, 'keypoints', 'keypoints/km5_Ключевые моменты.md'),
('testm5', 'Тестирование', 5, 'test', 'tests/testm5_Тестирование.md'),
('m6t1', 'Что такое отказоустойчивость и зачем она нужна', 6, 'topic', 'modules/m6/m6t1_Что такое отказоустойчивость и зачем она нужна.md'),
('m6t2', 'Disaster Recovery', 6, 'topic', 'modules/m6/m6t2_Disaster Recovery.md'),
('m6t3', 'Балансировка нагрузки', 6, 'topic', 'modules/m6/m6t3_Балансировка нагрузки.md'),
('p6', 'Отказоустойчивая инфраструктура', 6, 'practice', 'practices/p6_Отказоустойчивая инфраструктура.md'),
('km6', 'Ключевые моменты', 6, 'keypoints', 'keypoints/km6_Ключевые моменты.md'),
('testm6', 'Тестирование', 6, 'test', 'tests/testm6_Тестирование.md'),
('m7t1', 'Системы хранения и базы данных', 7, 'topic', 'modules/m7/m7t1_Системы хранения и базы данных.md'),
('m7t2', 'SQL vs NoSQL', 7, 'topic', 'modules/m7/m7t2_SQL vs NoSQL.md'),
('m7t3', 'Кеширование и очереди', 7, 'topic', 'modules/m7/m7t3_Кеширование и очереди.md'),
('m7t4', 'Работа с базами', 7, 'topic', 'modules/m7/m7t3_Работа с базами.md'),
('p7', 'База данных в облаке', 7, 'practice', 'practices/p7_База данных в облаке.md'),
('km7', 'Ключевые моменты', 7, 'keypoints', 'keypoints/km7_Ключевые моменты.md'),
('testm7', 'Тестирование', 7, 'test', 'tests/testm7_Тестирование.md'),
('m8t1', 'Основы информационной безопасности', 8, 'topic', 'modules/m8/m8t1_Основы информационной безопасности.md'),
('m8t2', 'Модель угроз', 8, 'topic', 'modules/m8/m8t2_Модель угроз.md'),
('m8t3', 'Best Practices', 8, 'topic', 'modules/m8/m8t3_Best Practices.md'),
('p8', 'Безопасная инфраструктура', 8, 'practice', 'practices/p8_Безопасная инфраструктура.md'),
('km8', 'Ключевые моменты', 8, 'keypoints', 'keypoints/km8_Ключевые моменты.md'),
('testm8', 'Тестирование', 8, 'test', 'tests/testm8_Тестирование.md'),
('m9t1', 'Архитектура микросервисов', 9, 'topic', 'modules/m9/m9t1_Архитектура микросервисов.md'),
('m9t2', 'Что такое микросервисы', 9, 'topic', 'modules/m9/m9t2_Что такое микросервисы.md'),
('m9t3', 'Kubernetes Administration', 9, 'topic', 'modules/m9/m9t3_Kubernetes Administration.md'),
('p9', 'Микросервисная архитектура', 9, 'practice', 'practices/p9_Микросервисная архитектура.md'),
('km9', 'Ключевые моменты', 9, 'keypoints', 'keypoints/km9_Ключевые моменты.md'),
('testm9', 'Тестирование', 9, 'test', 'tests/testm9_Тестирование.md'),
('m10t1', 'Ручное управление серверами', 10, 'topic', 'modules/m10/m10t1_Ручное управление серверами.md'),
('m10t2', 'ispmanger — панель управления', 10, 'topic', 'modules/m10/m10t2_ispmanger — панель управления.md'),
('p10', 'Полное построение инфраструктуры', 10, 'practice', 'practices/p10_Полное построение инфраструктуры.md'),
('km10', 'Ключевые моменты', 10, 'keypoints', 'keypoints/km10_Ключевые моменты.md'),
('testm10', 'Тестирование', 10, 'test', 'tests/testm10_Тестирование.md'),
('final_project', 'Инфраструктура сайта', 11, 'practice', 'projects/final_project_Инфраструктура сайта.md'),
('m12t1', 'Сравнение облачных провайдеров', 12, 'topic', 'modules/m12/m12t1_Сравнение облачных провайдеров.md'),
('m12t2', 'Организация сети, вычислительные мощности, балансировщики', 12, 'topic', 'modules/m12/m12t2_Организация сети, вычислительные мощности, балансировщики.md'),
('m12t3', 'Безопасность в облаке', 12, 'topic', 'modules/m12/m12t3_Безопасность в облаке.md'),
('m12t4', 'Кластеры и управляемые сервисы', 12, 'topic', 'modules/m12/m12t4_Кластеры и управляемые сервисы.md'),
('p12', 'Масштабируемая облачная инфраструктура', 12, 'practice', 'practices/p12_Масштабируемая облачная инфраструктура.md'),
('km12', 'Ключевые моменты', 12, 'keypoints', 'keypoints/km12_Ключевые моменты.md'),
('testm11', 'Тестирование', 12, 'test', 'tests/testm11_Тестирование.md'),
('m13t1', 'Как ИИ меняет DevOps', 13, 'topic', 'modules/m13/m13t1_Как ИИ меняет DevOps.md'),
('m13t2', 'Безопасность в работе с ИИ', 13, 'topic', 'modules/m13/m13t2_Безопасность в работе с ИИ.md'),
('m13t3', 'ИИ как ассистент разработчика', 13, 'topic', 'modules/m13/m13t3_ИИ как ассистент разработчика.md'),
('m13t4', 'ИИ в инфраструктуре разработки', 13, 'topic', 'modules/m13/m13t4_ИИ в инфраструктуре разработки.md'),
('m13t5', 'Поиск работы с помощью генеративного ИИ', 13, 'topic', 'modules/m13/m13t5_Поиск работы с помощью генеративного ИИ.md'),
('m13t6', 'Нейросети для технических задач', 13, 'topic', 'modules/m13/m13t6_Нейросети для технических задач.md'),
('m14t1', 'Английский для кодера', 14, 'topic', 'modules/m14/m14t1_Английский для кодера.md'),
('roadmap', 'DevOps Roadmap', 99, 'topic', 'misc/DevOps Roadmap.md');